import Layout from '@/components/Layout';
import { motion } from 'framer-motion';
import { Database, Plus } from 'lucide-react';
import Link from 'next/link';

export default function UploadPage({ user, loading }) {
    if (loading) return null;
    if (!user) return null;

    return (
        <Layout user={user}>
            <div className="flex justify-between items-center mb-10">
                <div>
                    <h2 className="text-3xl font-bold font-outfit uppercase tracking-tight">Datasets</h2>
                    <p className="text-slate-400">Manage and upload your social data for training</p>
                </div>
                <Link href="/train">
                    <button className="btn-primary flex items-center space-x-2">
                        <Plus size={20} />
                        <span>New Dataset</span>
                    </button>
                </Link>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    className="glass-card p-6 flex flex-col items-center justify-center text-center space-y-4 border-dashed border-2 border-white/5 bg-transparent opacity-60"
                >
                    <div className="w-16 h-16 bg-white/5 rounded-2xl flex items-center justify-center text-slate-500">
                        <Database size={32} />
                    </div>
                    <div>
                        <h4 className="font-bold text-slate-400">Automated Training Set</h4>
                        <p className="text-xs text-slate-500 mt-1">Generated by System (1,000 Rows)</p>
                    </div>
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-500 border border-emerald-500/20 font-bold uppercase">Active</span>
                </motion.div>
            </div>

            <div className="mt-12 text-center py-20 bg-white/5 border border-white/5 rounded-3xl">
                <Database size={48} className="text-slate-700 mx-auto mb-4" />
                <h3 className="text-xl font-bold text-slate-500">More data results in better accuracy</h3>
                <p className="text-slate-600 max-w-md mx-auto mt-2">
                    The system currently uses the default training set. Uploading unique CSV data will improve the localized prediction accuracy.
                </p>
            </div>
        </Layout>
    );
}
